import type { DomainId, Question, TrackId } from './types'

type SupplementalSeed = readonly [
  id: string,
  trackId: TrackId,
  domainId: DomainId,
  prompt: string,
  choices: readonly [string, string, string, string],
  correctIndex: number,
  rationale: string,
  sourceId: Question['sourceId'],
]

const seeds: readonly SupplementalSeed[] = [
  [
    'mix-ww-01',
    'world-warrior',
    'ww-spacing',
    'Cabinet time machine: which release first added Cammy, T. Hawk, Fei Long, and Dee Jay?',
    [
      'Champion Edition',
      'Hyper Fighting',
      'Super Street Fighter II',
      'Super Street Fighter II Turbo',
    ],
    2,
    'Super Street Fighter II introduced the four New Challengers.',
    'capcom-sfii',
  ],
  [
    'mix-ww-02',
    'world-warrior',
    'ww-spacing',
    'Which Street Fighter II release first put Super Combos and a Super Meter into play?',
    [
      'Hyper Fighting',
      'Super Street Fighter II',
      'Super Street Fighter II Turbo',
      'Champion Edition',
    ],
    2,
    'Super Street Fighter II Turbo introduced the Super Meter and Super Combos.',
    'capcom-sfii',
  ],
  [
    'mix-ww-03',
    'world-warrior',
    'ww-spacing',
    'Who was not one of the original eight playable World Warriors?',
    ['Guile', 'Cammy', 'E. Honda', 'Dhalsim'],
    1,
    'Cammy arrived later as one of the New Challengers in Super Street Fighter II.',
    'capcom-sfii',
  ],
  [
    'mix-ww-04',
    'world-warrior',
    'ww-control',
    'A North American player says “Claw.” Which Japanese-release name are they disambiguating?',
    ['Balrog', 'Vega', 'M. Bison', 'Sagat'],
    1,
    'The regional shorthand maps Japanese Vega to the North American claw fighter.',
    'capcom-sfii',
  ],
  [
    'mix-ww-05',
    'world-warrior',
    'ww-control',
    'Which input family launches Guile’s Sonic Boom?',
    [
      'Quarter-circle forward plus punch',
      'Charge back, then forward plus punch',
      'Dragon-punch motion plus punch',
      'A full-circle motion plus punch',
    ],
    1,
    'Sonic Boom is a back-to-forward charge special.',
    'capcom-controls',
  ],
  [
    'mix-ww-06',
    'world-warrior',
    'ww-control',
    'What motion is normally used for Ryu’s Hadoken?',
    [
      'Charge down, then up plus punch',
      'Quarter-circle forward plus punch',
      'Dragon-punch motion plus kick',
      'Charge back, then forward plus kick',
    ],
    1,
    'Hadoken uses the familiar down-to-forward quarter-circle plus punch.',
    'capcom-controls',
  ],
  [
    'mix-ww-07',
    'world-warrior',
    'ww-control',
    'Zangief closes the gap and lands a Spinning Piledriver. What kind of attack was it?',
    ['Charge anti-air', 'Command throw', 'Projectile', 'Overhead normal'],
    1,
    'Spinning Piledriver is a close-range command throw rather than a blockable strike.',
    'capcom-offense',
  ],
  [
    'mix-ww-08',
    'world-warrior',
    'ww-defense',
    'What makes an action a reversal?',
    [
      'It reflects a projectile',
      'It is performed immediately as recovery or wake-up ends',
      'It swaps corner positions',
      'It cancels a special into a taunt',
    ],
    1,
    'A reversal is timed for the first actionable moment after stun or knockdown recovery.',
    'capcom-offense',
  ],
  [
    'mix-ww-09',
    'world-warrior',
    'ww-defense',
    'Which chip-damage rule best describes classic Street Fighter II?',
    [
      'Blocked normals always deal chip',
      'Blocked specials can deal small damage while most normals do not',
      'Chip applies only during dizzy',
      'Blocking removes all damage',
    ],
    1,
    'Special moves can chip a blocking defender; ordinary blocked normals generally do not.',
    'capcom-sfii',
  ],
  [
    'mix-ww-10',
    'world-warrior',
    'ww-defense',
    'Your last three jump-ins were cleanly anti-aired. What is the smartest next beat?',
    [
      'Repeat the same jump with a heavier button',
      'Approach on the ground, bait, or change the jump timing',
      'Try to pause the cabinet',
      'Hold down in mid-air to block',
    ],
    1,
    'Changing timing or using the ground forces the defender to solve a new problem.',
    'capcom-offense',
  ],
  [
    'mix-ww-11',
    'world-warrior',
    'ww-spacing',
    'Long-range projectiles plus a charge anti-air usually describe which archetype?',
    ['Grappler', 'Charge zoner', 'Rushdown', 'Puppet character'],
    1,
    'A charge zoner controls approach lanes, then checks jumps with a charged anti-air.',
    'capcom-offense',
  ],
  [
    'mix-ww-12',
    'world-warrior',
    'ww-spacing',
    'In Super Turbo, what is the biggest system tradeoff when selecting an “Old” character version?',
    [
      'It gives up the Super Meter for an earlier move-property set',
      'It disables all special moves',
      'It doubles health',
      'It grants Akuma’s move set',
    ],
    0,
    'Old versions preserve earlier properties but do not use the Super Meter.',
    'capcom-sfii',
  ],
  [
    'mix-ww-13',
    'world-warrior',
    'ww-spacing',
    'Which New Challenger brought Spiral Arrow and Cannon Spike to Super Street Fighter II?',
    ['Chun-Li', 'Cammy', 'Fei Long', 'Dee Jay'],
    1,
    'Those specials belong to Cammy, one of the four New Challengers.',
    'capcom-sfii',
  ],
  [
    'mix-ww-14',
    'world-warrior',
    'ww-control',
    'What must happen before Guile can release a Sonic Boom?',
    [
      'Back must be held long enough to establish charge',
      'Punch must be held for two full seconds',
      'The lever must return to neutral three times',
      'Guile must first block a projectile',
    ],
    0,
    'The exact timing is version-sensitive, but the move always depends on a sustained back charge.',
    'capcom-controls',
  ],
  [
    'mix-ww-15',
    'world-warrior',
    'ww-spacing',
    'Two ordinary single-hit projectiles meet mid-screen. What normally happens?',
    [
      'They pass through',
      'They collide and negate each other',
      'They create Super Meter',
      'The lower-health player takes damage',
    ],
    1,
    'Matching single-hit projectiles normally cancel on contact.',
    'capcom-sfii',
  ],
  [
    'mix-ww-16',
    'world-warrior',
    'ww-spacing',
    'Which Street Fighter II version first opened the door to mirror matches?',
    [
      'The World Warrior',
      'Champion Edition',
      'Super Street Fighter II',
      'Super Street Fighter II Turbo',
    ],
    1,
    'Champion Edition allowed both players to choose the same fighter with alternate colors.',
    'capcom-sfii',
  ],
  [
    'mix-ww-17',
    'world-warrior',
    'ww-control',
    'In Japanese arcade naming, who is M. Bison?',
    [
      'The boxer called Balrog in North America',
      'The claw fighter called Vega in North America',
      'The dictator called M. Bison in North America',
      'Sagat',
    ],
    0,
    'Japanese M. Bison maps to the North American boxer name, Balrog.',
    'capcom-sfii',
  ],
  [
    'mix-ww-18',
    'world-warrior',
    'ww-control',
    'Which directional sequence is the classic dragon-punch motion?',
    [
      'Down, down-forward, forward',
      'Forward, down, down-forward',
      'Charge down, then up',
      'Back, down-back, down',
    ],
    1,
    'The dragon-punch motion is forward, down, down-forward—also written 623.',
    'capcom-controls',
  ],
  [
    'mix-ww-19',
    'world-warrior',
    'ww-defense',
    'What unmistakable visual says a classic Street Fighter II character is dizzy?',
    [
      'A red health-bar outline',
      'Stars, birds, or similar icons circling the head',
      'A translucent sprite',
      'A ten-second number above the fighter',
    ],
    1,
    'The helpless dizzy state is signaled by animated icons circling the character’s head.',
    'capcom-sfii',
  ],
  [
    'mix-ww-20',
    'world-warrior',
    'ww-spacing',
    'What is Dhalsim trying to make you fight through in neutral?',
    [
      'Fast command-throw rushdown',
      'Long limbs and Yoga Fire controlling distance',
      'Wall-combo routes',
      'Repeated dragon-punch loops',
    ],
    1,
    'Dhalsim’s classic plan is to control distant lanes with extended normals and projectiles.',
    'capcom-sfii',
  ],
  [
    'mix-ww-21',
    'world-warrior',
    'ww-spacing',
    'Which secret boss debuted in Super Street Fighter II Turbo?',
    ['Gouki / Akuma', 'Gill', 'M. Bison', 'Evil Ryu'],
    0,
    'Gouki, called Akuma outside Japan, debuted as Super Turbo’s secret challenger.',
    'capcom-sfii',
  ],
  [
    'mix-ww-22',
    'world-warrior',
    'ww-defense',
    'What makes wake-up pressure “meaty”?',
    [
      'The attack’s active frames overlap the defender’s first wake-up moments',
      'Only a heavy button is used',
      'The combo exceeds half a life bar',
      'The attacker taunts while crouching',
    ],
    0,
    'Meaty timing overlaps later active frames with wake-up, tightening the defender’s response window.',
    'capcom-offense',
  ],
  [
    'mix-ww-23',
    'world-warrior',
    'ww-spacing',
    'Which archetype accepts a difficult approach in exchange for terrifying command-grab damage?',
    ['Grappler', 'Zoner', 'Puppet character', 'Stance switcher'],
    0,
    'Grapplers work to enter command-throw range, where their reward becomes enormous.',
    'capcom-offense',
  ],
  [
    'mix-ww-24',
    'world-warrior',
    'ww-spacing',
    'Which important tool did Chun-Li gain in Hyper Fighting?',
    ['Kikoken', 'A full-circle throw', 'Double health', 'Akuma’s teleport'],
    0,
    'Hyper Fighting added Chun-Li’s Kikoken projectile.',
    'capcom-sfii',
  ],
  [
    'mix-if-01',
    'iron-fist',
    'if-control',
    'Quick notation check: which buttons are left punch and right punch?',
    ['1 and 2', '3 and 4', '1 and 3', '2 and 4'],
    0,
    'Tekken maps 1 and 2 to the left and right arms.',
    'bandai-guide',
  ],
  [
    'mix-if-02',
    'iron-fist',
    'if-control',
    'Which buttons are left kick and right kick?',
    ['1 and 2', '3 and 4', '1 and 4', '2 and 3'],
    1,
    'Tekken maps 3 and 4 to the left and right legs.',
    'bandai-guide',
  ],
  [
    'mix-if-03',
    'iron-fist',
    'if-control',
    'In a command such as f, N, d, d/f+2, what does N demand?',
    [
      'Press the next attack',
      'Return briefly to neutral',
      'Enter a stance',
      'Hold down for one second',
    ],
    1,
    'N marks a neutral directional input between the surrounding commands.',
    'bandai-guide',
  ],
  [
    'mix-if-04',
    'iron-fist',
    'if-control',
    'When can a while-standing move come out?',
    [
      'While running forward',
      'During the rise from crouching',
      'While holding standing guard',
      'During a taunt',
    ],
    1,
    'While-standing moves are accessed as the fighter transitions out of crouch.',
    'bandai-guide',
  ],
  [
    'mix-if-05',
    'iron-fist',
    'if-control',
    'What does FC mean in a Tekken move list?',
    ['Frame Counter', 'Full Crouch', 'Forward Cancel', 'Fast Combo'],
    1,
    'FC identifies the sustained Full Crouch state.',
    'bandai-guide',
  ],
  [
    'mix-if-06',
    'iron-fist',
    'if-movement',
    'Which basic standing guard input covers high and mid strikes?',
    ['Back', 'Down-back', 'Down', 'Forward'],
    0,
    'Back is the standard standing guard; crouch guard gives up protection against mids.',
    'bandai-guide',
  ],
  [
    'mix-if-07',
    'iron-fist',
    'if-control',
    'A standard throw shows both hands extending. Which break should you read?',
    ['1', '2', '1+2', '3+4'],
    2,
    'A two-hand throw animation commonly signals a 1+2 break.',
    'bandai-guide',
  ],
  [
    'mix-if-08',
    'iron-fist',
    'if-movement',
    'What is the practical purpose of Korean Backdash movement?',
    [
      'Chain backdashes by canceling recovery to create space',
      'Automatically parry lows',
      'Double attack speed',
      'Regenerate health',
    ],
    0,
    'The technique improves backward movement by canceling one backdash into the next sequence.',
    'bandai-3d',
  ],
  [
    'mix-if-09',
    'iron-fist',
    'if-movement',
    'A low is coming. Which defensive family answers it?',
    [
      'Standing back guard',
      'Down-back guard or a correctly timed low parry',
      'Up-forward',
      'Double neutral',
    ],
    1,
    'Crouch guard blocks lows, while a properly timed low parry can turn defense into a conversion.',
    'bandai-guide',
  ],
  [
    'mix-if-10',
    'iron-fist',
    'if-movement',
    'The opponent keeps swinging a linear move on the same beat. What is the high-value adjustment?',
    [
      'Sidestep or sidewalk the timing and punish the whiff',
      'Stay crouched forever',
      'Mash jabs blindly',
      'Backdash into the wall',
    ],
    0,
    'Predictable linear attacks invite lateral movement followed by a whiff punish.',
    'bandai-guide',
  ],
  [
    'mix-if-11',
    'iron-fist',
    'if-movement',
    'Which title gave every fighter a sidestep dodge and pushed Tekken decisively into 3D movement?',
    ['Tekken', 'Tekken 2', 'Tekken 3', 'Tekken Tag Tournament 2'],
    2,
    'PlayStation’s series history identifies universal sidestep dodges as a Tekken 3 addition.',
    'playstation-tekken-history',
  ],
  [
    'mix-if-12',
    'iron-fist',
    'if-launch',
    'What defines the match structure of the original Tekken Tag Tournament?',
    [
      'Two-character teams with in-battle switching',
      'Three-on-three elimination',
      'Infinite super meters',
      'First-person combat',
    ],
    0,
    'Tag Tournament centers on choosing two fighters and swapping between them during battle.',
    'playstation-tekken-history',
  ],
  [
    'mix-if-13',
    'iron-fist',
    'if-launch',
    'How does a benched partner interact with recoverable red health in Tekken Tag Tournament?',
    [
      'It gradually recovers off-screen',
      'Blocking on-screen restores it',
      'It becomes bonus damage',
      'It can never return',
    ],
    0,
    'Tagging out protects the damaged partner and allows recoverable health to return.',
    'playstation-tekken-history',
  ],
  [
    'mix-if-14',
    'iron-fist',
    'legacy-t5dr',
    'Which newcomers arrived with Tekken 5: Dark Resurrection?',
    [
      'Lili and Sergei Dragunov',
      'Jin and Xiaoyu',
      'Bryan and Eddy',
      'Hwoarang and Forest Law',
    ],
    0,
    'Lili and Dragunov debuted in the Dark Resurrection revision.',
    'playstation-t5dr',
  ],
  [
    'mix-if-15',
    'iron-fist',
    'legacy-t5dr',
    'How should Armor King’s Dark Resurrection appearance be described?',
    [
      'A returning playable masked wrestler',
      'A Street Fighter guest',
      'A cheat-only boss',
      'A costume with no distinct move set',
    ],
    0,
    'Dark Resurrection brought Armor King back as a playable roster member.',
    'playstation-t5dr',
  ],
  [
    'mix-if-16',
    'iron-fist',
    'if-movement',
    'What does low crush communicate about a move?',
    [
      'Its movement state evades low attacks',
      'It breaks the stage floor',
      'It doubles damage on crouchers',
      'It guarantees stun',
    ],
    0,
    'Low-crush states avoid lows, often because the attacker becomes airborne.',
    'bandai-guide',
  ],
  [
    'mix-if-17',
    'iron-fist',
    'if-movement',
    'What does high crush communicate about a move?',
    [
      'Its movement state passes under high attacks',
      'It targets airborne opponents',
      'It breaks standing guard',
      'It guarantees a wall splat',
    ],
    0,
    'High-crush states duck beneath highs during the relevant part of the move.',
    'bandai-guide',
  ],
  [
    'mix-if-18',
    'iron-fist',
    'if-launch',
    'The opponent sticks to the wall after a heavy hit. What opportunity did the wall splat create?',
    [
      'A wall-combo follow-up',
      'A full-health recovery',
      'An automatic stage transition',
      'A reset to center',
    ],
    0,
    'A wall splat holds the defender at the boundary long enough for a specialized follow-up.',
    'bandai-3d',
  ],
  [
    'mix-if-19',
    'iron-fist',
    'if-movement',
    'Which Tekken 3 newcomer is famous for capoeira movement and sweeping attacks?',
    ['Eddy Gordo', 'Hwoarang', 'Jin Kazama', 'Forest Law'],
    0,
    'Eddy Gordo debuted in Tekken 3 with a capoeira-inspired style.',
    'playstation-tekken-history',
  ],
  [
    'mix-if-20',
    'iron-fist',
    'if-movement',
    'What broad design direction did Tekken 5 take after Tekken 4?',
    [
      'Faster traditional movement with refined walls and stages',
      'Removal of every wall',
      'A 2D side-scroller format',
      'Removal of juggle combos',
    ],
    0,
    'Tekken 5 returned emphasis to brisk movement and more standardized arena layouts while retaining walls.',
    'playstation-tekken-history',
  ],
  [
    'mix-if-21',
    'iron-fist',
    'if-launch',
    'What turns an ordinary response into block punishment?',
    [
      'The reply is guaranteed during an unsafe move’s recovery',
      'The defender takes chip damage',
      'The opponent happens to be guarding',
      'A taunt shortens recovery',
    ],
    0,
    'Block punishment uses frame advantage after guarding an unsafe attack to land a guaranteed response.',
    'bandai-guide',
  ],
  [
    'mix-if-22',
    'iron-fist',
    'if-launch',
    'The opponent’s launcher misses inches from your face. What is a whiff punish?',
    [
      'Hitting its recovery before the opponent can defend',
      'Attacking crouch guard',
      'Breaking a throw',
      'Parrying a jab',
    ],
    0,
    'A whiff punish attacks the recovery of a move that failed to connect.',
    'bandai-guide',
  ],
  [
    'mix-if-23',
    'iron-fist',
    'if-launch',
    'Why is a fast standing jab a vital line in a punishment chart?',
    [
      'It answers mildly unsafe moves before they recover',
      'It removes nearly all health',
      'Every jab launches',
      'It automatically breaks throws',
    ],
    0,
    'Fast jabs are common baseline punishers, though the exact button and speed must be checked per character and version.',
    'bandai-guide',
  ],
  [
    'mix-if-24',
    'iron-fist',
    'if-launch',
    'What is a launcher’s main job in a Tekken combo plan?',
    [
      'Put the opponent airborne for a juggle',
      'Push directly to full screen',
      'Reset both health bars',
      'Swap stances without attacking',
    ],
    0,
    'A launcher creates the airborne state that makes a juggle route possible.',
    'bandai-guide',
  ],
  [
    'mix-if-25',
    'iron-fist',
    'if-launch',
    'You block a very unsafe low and recover in crouch. Which punish family should you check first?',
    [
      'A while-standing launcher or punish',
      'A standing jab regardless of timing',
      'A sidestep',
      'A backdash',
    ],
    0,
    'Because low guard leaves you crouching, while-standing options are the natural punishment branch.',
    'bandai-guide',
  ],
  [
    'mix-if-26',
    'iron-fist',
    'if-launch',
    'Your scaled combo reaches the wall. What decision matters more than blindly adding hits?',
    [
      'Choose among damage, positioning, and the next wake-up situation',
      'Pause for a frame-data lookup',
      'Tag out in mid-air',
      'Stop and hold guard',
    ],
    0,
    'A strong wall route weighs the ender’s damage against position and okizeme value.',
    'bandai-guide',
  ],
  [
    'mix-if-27',
    'iron-fist',
    'if-launch',
    'What creates a counter hit?',
    [
      'Striking during the opponent’s attack startup',
      'Blocking three attacks',
      'Pressing 3+4 to parry',
      'Hitting any grounded opponent',
    ],
    0,
    'Counter hits catch an opponent starting an attack and can unlock stronger move properties.',
    'bandai-guide',
  ],
  [
    'mix-if-28',
    'iron-fist',
    'if-launch',
    'A move is listed as -15 on block. What should an analyst verify before calling the punish “free”?',
    [
      'Whether the chosen character and version have an in-range i15 launcher',
      'Whether a jab deals 90 percent',
      'Whether -15 is actually safe',
      'Whether throws are unblockable',
    ],
    0,
    'Frame advantage sets the time budget, but roster, version, range, and stance determine the real punish.',
    'bandai-guide',
  ],
  [
    'mix-if-29',
    'iron-fist',
    'if-launch',
    'What does wall carry describe?',
    [
      'Routing a juggle to move the opponent toward the wall',
      'Moving the arena wall itself',
      'Holding guard at the wall',
      'A Mishima-only stance',
    ],
    0,
    'Wall-carry routes trade or optimize hits to gain forward displacement and a wall conversion.',
    'bandai-guide',
  ],
  [
    'mix-if-30',
    'iron-fist',
    'if-launch',
    'A move is -12 on block. Which response best respects that window?',
    [
      'A verified i10–i12 punish',
      'A 20-frame launcher',
      'An untested slow sweep',
      'Waiting two seconds',
    ],
    0,
    'A punish must start within the available disadvantage window and still reach the opponent.',
    'bandai-guide',
  ],
]

export const supplementalQuestions: readonly Question[] = seeds.map(
  ([
    id,
    trackId,
    domainId,
    prompt,
    choices,
    correctIndex,
    rationale,
    sourceId,
  ]) => ({
    id,
    trackId,
    domainId,
    prompt,
    choices,
    correctIndex,
    rationale,
    sourceId,
    reviewedAt: '2026-07-28',
    rights: 'original-demo-copy',
  }),
)
